"""
pdf_generator.py - PDF Report Generator
Creates beautiful PDF reports from video Q&A sessions
"""

import os
from datetime import datetime
from fpdf import FPDF
import re


class YouTubeQAPDF(FPDF):
    """Custom PDF class with header and footer."""

    def __init__(self, video_metadata: dict):
        super().__init__()
        self.video_metadata = video_metadata
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        """PDF header with branding."""
        # Background bar
        self.set_fill_color(15, 23, 42)  # Dark navy
        self.rect(0, 0, 210, 18, "F")

        # Logo/Title text
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(99, 102, 241)  # Indigo
        self.set_xy(10, 4)
        self.cell(0, 10, "YouTube Q&A Genius", ln=False)

        # Right side - page info
        self.set_font("Helvetica", "", 8)
        self.set_text_color(156, 163, 175)
        self.set_xy(0, 6)
        self.cell(200, 5, f"Page {self.page_no()}", align="R")

        self.ln(14)

    def footer(self):
        """PDF footer."""
        self.set_y(-15)
        self.set_fill_color(15, 23, 42)
        self.rect(0, self.get_y(), 210, 15, "F")
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(107, 114, 128)
        self.cell(0, 10, f"Generated by YouTube Q&A Genius | {datetime.now().strftime('%B %d, %Y')}", align="C")


def clean_text(text: str) -> str:
    """Remove markdown formatting and special characters for PDF."""
    # Remove markdown bold/italic
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = re.sub(r"#{1,6}\s", "", text)
    # Remove emojis and special unicode
    text = text.encode("latin-1", "ignore").decode("latin-1")
    return text.strip()


def generate_qa_pdf(
    video_metadata: dict,
    chat_history: list,
    summary: str = None,
    key_points: str = None,
    output_path: str = None,
) -> str:
    """
    Generate a comprehensive PDF report of the Q&A session.
    
    Args:
        video_metadata: Dict with title, author, url, thumbnail
        chat_history: List of {role, content} dicts
        summary: Optional video summary text
        key_points: Optional key points text
        output_path: Where to save the PDF
    
    Returns:
        Path to generated PDF
    """
    if not output_path:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        video_id = video_metadata.get("video_id", "video")
        output_path = f"./qa_report_{video_id}_{timestamp}.pdf"

    pdf = YouTubeQAPDF(video_metadata)
    pdf.add_page()

    # ─── COVER SECTION ────────────────────────────────────────────────────────
    # Title banner
    pdf.set_fill_color(15, 23, 42)
    pdf.rect(0, pdf.get_y(), 210, 45, "F")

    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(255, 255, 255)
    pdf.set_x(10)
    title = clean_text(video_metadata.get("title", "YouTube Video"))
    # Truncate long titles
    if len(title) > 60:
        title = title[:57] + "..."
    pdf.multi_cell(190, 10, title, align="L")

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(156, 163, 175)
    pdf.set_x(10)
    pdf.cell(0, 8, f"Channel: {clean_text(video_metadata.get('author', 'Unknown'))}", ln=True)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_x(10)
    pdf.cell(0, 6, f"URL: {video_metadata.get('url', '')}", ln=True)
    pdf.ln(8)

    # Generated info
    pdf.set_fill_color(30, 41, 59)
    pdf.set_x(10)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(190, 8, f"  Report Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}  |  Q&A Sessions: {len([m for m in chat_history if m['role'] == 'user'])} Questions", 
             fill=True, ln=True)
    pdf.ln(10)

    # ─── DIVIDER ──────────────────────────────────────────────────────────────
    def draw_section_header(title_text, color=(99, 102, 241)):
        pdf.set_fill_color(*color)
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(190, 10, f"  {title_text}", fill=True, ln=True)
        pdf.ln(3)

    # ─── SUMMARY SECTION ──────────────────────────────────────────────────────
    if summary:
        draw_section_header("VIDEO SUMMARY", (79, 70, 229))
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 41, 59)
        summary_clean = clean_text(summary)
        pdf.multi_cell(190, 6, summary_clean)
        pdf.ln(8)

    # ─── KEY POINTS SECTION ───────────────────────────────────────────────────
    if key_points:
        draw_section_header("KEY POINTS", (16, 185, 129))
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 41, 59)
        kp_clean = clean_text(key_points)
        pdf.multi_cell(190, 6, kp_clean)
        pdf.ln(8)

    # ─── Q&A SECTION ──────────────────────────────────────────────────────────
    if chat_history:
        user_messages = [m for m in chat_history if m["role"] == "user"]
        if user_messages:
            draw_section_header(f"Q&A SESSION ({len(user_messages)} Questions)", (234, 88, 12))
            pdf.ln(2)

        q_num = 0
        for i, message in enumerate(chat_history):
            if message["role"] == "user":
                q_num += 1
                # Question box
                pdf.set_fill_color(239, 246, 255)
                pdf.set_draw_color(99, 102, 241)
                pdf.set_font("Helvetica", "B", 10)
                pdf.set_text_color(29, 78, 216)
                question_text = clean_text(message["content"])
                pdf.multi_cell(190, 8, f"  Q{q_num}: {question_text}", fill=True, border="L")
                pdf.ln(2)

            elif message["role"] == "assistant":
                # Answer
                pdf.set_font("Helvetica", "", 10)
                pdf.set_text_color(30, 41, 59)
                answer_text = clean_text(message["content"])
                # Limit very long answers
                if len(answer_text) > 2000:
                    answer_text = answer_text[:2000] + "... [truncated for PDF]"
                pdf.set_x(15)
                pdf.multi_cell(185, 6, answer_text)
                pdf.ln(6)

                # Separator
                pdf.set_draw_color(226, 232, 240)
                pdf.line(10, pdf.get_y(), 200, pdf.get_y())
                pdf.ln(4)

    # ─── FOOTER NOTE ──────────────────────────────────────────────────────────
    pdf.ln(5)
    pdf.set_fill_color(248, 250, 252)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(107, 114, 128)
    pdf.multi_cell(190, 6,
        "This report was automatically generated by YouTube Q&A Genius powered by LangChain + ChromaDB + Groq AI. "
        "All answers are based on the video transcript and may not capture visual content.",
        fill=True)

    # Save PDF
    pdf.output(output_path)
    return output_path